// /* 
//     caution1 : 안내견 동반 가능
//     caution2 : 가발착용 가능
//     caution3 : 임산부 가능
//     caution4 : 휠체어 가능
//     caution5 : 차일드 스위치 사용 가능
//     caution6 : 싱글 라이더 사용 가능
//     caution7 : 자막 표시 안경 이용 가능(일본어)

// */




// const attraction_wrap = [
//     {
//         idx : "1",
//         name : "42nd 스트리트 스튜디오 ~그리팅 갤러리~",
//         image : "attraction1",
//         explanation : "뉴욕 한켠에 위치한 ‘42nd 스트리트 스튜디오’는 화제의 아티스트들이 앞다투어 전시회를 연다는 유명한 갤러리. 그중 인기 최고의 아티스트, 미니언과 스누피가 여러분을 아틀리에로 초대해 작품을 공개! 새로운 영감을 찾아 헤매던 중이라 어쩌면 당신에게 도와달라고 할지도?! 작품이 완성되면 함께 기념사진을 찍어 보자!",
//         caution1 : "1",
//         caution2 : "1",
//         caution3 : "1",
//         caution4 : "1",
//         caution5 : "0",
//         caution6 : "0",
//         caution7 : "0",
//     },
//     {
//         idx : "2",
//         name : "그로버 콘스트럭션 컴퍼니" ,
//         image : "attraction2",
//         explanation : "길쭉한 모양의 블록과 톱니바퀴 모양의 블록. 여러 가지 모양의 커다란 블록이 한가득! 무엇을 만들까요? 마음대로 자유롭게 만들고 즐겨요!",
//         caution1 : "0",
//         caution2 : "0",
//         caution3 : "0",
//         caution4 : "0",
//         caution5 : "0",
//         caution6 : "0",
//         caution7 : "0",
//     },
//     {
//         idx : "3",
//         name : "날아라 스누피" ,
//         image : "attraction3",
//         explanation : "스누피와 함께 하늘을 날자! 직접 조종해서 피너츠 친구들의 주변을 돌며 날아올랐다가 저공으로 비행해 보자. 하늘 높이 날아서 구름 위에 있는 것처럼 둥실둥실 떠있는 기분을 맛보세요.",
//         caution1 : "0",
//         caution2 : "1",
//         caution3 : "0",
//         caution4 : "1",
//         caution5 : "1",
//         caution6 : "0",
//         caution7 : "0",
//     },
//     {
//         idx : "4",
//         name : "더 플라잉 다이너소어" ,
//         image : "attraction4",
//         explanation : "뉴욕 한켠에 위치한 ‘42nd 스트리트 스튜디오’는 화제의 아티스트들이 앞다투어 전시회를 연다는 유명한 갤러리. 그중 인기 최고의 아티스트, 미니언과 스누피가 여러분을 아틀리에로 초대해 작품을 공개! 새로운 영감을 찾아 헤매던 중이라 어쩌면 당신에게 도와달라고 할지도?! 작품이 완성되면 함께 기념사진을 찍어 보자!",
//         caution1 : "0",
//         caution2 : "0",
//         caution3 : "0",
//         caution4 : "1",
//         caution5 : "1",
//         caution6 : "1",
//         caution7 : "0",
//     },
//     {
//         idx : "5",
//         name : "마리오 카트: 쿠파의 도전장™" ,
//         image : "attraction5",
//         explanation :  `그 유명한 마리오 카트의 세계와 놀라움 가득한 갖가지 코스가 바로 눈앞에 등장한다! 등껍질을 던져 적을 격퇴하면서 마리오 그리고 피치공주와 함께 돌진하라! 파크만의 최신 기술로 실현되는 세계 최초*의 마리오 카트 체험에 두근두근 흥분이 멈추지 않는다!<br/>
//         * 마리오 카트 및 마리오의 게임 속 세계를 테마로 한 테마파크의 오리지널 어트랙션, 게임을 취급하는 시설을 대상으로 한 자사 조사.`,
//         caution1 : "0",
//         caution2 : "1",
//         caution3 : "0",
//         caution4 : "1",
//         caution5 : "1",
//         caution6 : "1",
//         caution7 : "0",
//     },
//     {
//         idx : "6",
//         name : "만나기",
//         image : "attraction6",
//         explanation : `그 유명한 마리오 카트의 세계와 놀라움 가득한 갖가지 코스가 바로 눈앞에 등장한다! 등껍질을 던져 적을 격퇴하면서 마리오 그리고 피치공주와 함께 돌진하라! 파크만의 최신 기술로 실현되는 세계 최초*의 마리오 카트 체험에 두근두근 흥분이 멈추지 않는다!<br/>
//         * 마리오 카트 및 마리오의 게임 속 세계를 테마로 한 테마파크의 오리지널 어트랙션, 게임을 취급하는 시설을 대상으로 한 자사 조사.`,
//         caution1 : "0",
//         caution2 : "1",
//         caution3 : "0",
//         caution4 : "1",
//         caution5 : "1",
//         caution6 : "1",
//         caution7 : "0",
//     },
//     {
//         idx : "7",
//         name : "몹피의 럭키 댄스 파티",
//         image : "attraction7",
//         explanation : "댄스파티에 오신 것을 환영합니다. 하트와 별이 가득한 홀에서 DJ와 함께 음악에 맞춰 즐겁게 춤춰요! 몹피를 만날 수 있다면 행운이겠죠!",
//         caution1 : "0",
//         caution2 : "0",
//         caution3 : "0",
//         caution4 : "0",
//         caution5 : "0",
//         caution6 : "0",
//         caution7 : "0",
//     },
//     {
//         idx : "8",
//         name : "몹피의 벌룬 여행",
//         image : "attraction8",
//         explanation : "몹피가 여러분을 즐거운 풍선 여행으로 초대했어요. 푸른 하늘로 날아올라 원더랜드의 깜찍한 세계를 즐겨보아요. 핸들을 돌리면 곤돌라도 빙글빙글, 모두 다 함께 신나게 놀자!",
//         caution1 : "0",
//         caution2 : "1",
//         caution3 : "0",
//         caution4 : "1",
//         caution5 : "1",
//         caution6 : "0",
//         caution7 : "0",
//     },
//     {
//         idx : "9",
//         name : "미니언 그리팅",
//         image : "attraction9",
//         explanation : "‘미니언 파크’ 가장 안쪽의 유달리 눈에 띄는 그루의 저택. 그곳의 지하 연구실에 사는 미니언들이 가끔씩 저택 앞에 등장해요! 함께 사진을 찍고 교류하면서 서로 친해질 찬스입니다!",
//         caution1 : "0",
//         caution2 : "0",
//         caution3 : "0",
//         caution4 : "0",
//         caution5 : "0",
//         caution6 : "0",
//         caution7 : "0",
//     },
//     {
//         idx : "10",
//         name : "미니언 랠리",
//         image : "attraction10",
//         explanation : "성공하면 미니언들이 선물을 드려요. 생각지도 못했던 곳에 신기한 미니언이 숨어 있을지도?! 미니언 파크에 오면 스페이스 킬러 등의 게임 코너에서 책자를 손에 넣자!(유료)",
//         caution1 : "0",
//         caution2 : "0",
//         caution3 : "0",
//         caution4 : "0",
//         caution5 : "0",
//         caution6 : "0",
//         caution7 : "0",
//     },
//     {
//         idx : "11",
//         name : "미니언 메이헴",
//         image : "attraction11",
//         explanation : "거대 돔 스크린 위에 펼쳐지는 현장감 넘치는 영상과 함께 미니언들이 일으키는 뒤죽박죽 대소동 속으로 리얼하게 휩쓸려 들어가는 흥분 최고조의 라이드 어트랙션을 즐기자! 무대는 괴도 그루의 저택 겸 연구실. 그루가 발명한 특별한 차량을 타면 ‘미니언이 되기’ 위한 기상천외한 트레이닝 스타트! 수많은 미니언 & 그루의 세 딸과 함께 연구실 안을 어지럽게 뛰어다니기도 하고, 마음껏 신나게 날기도 하고, 그러다 땅끝까지 곤두박질! 인줄 알았더니 미니언과 그루 & 세 자매의 깊은 유대감에 생각지도 못하게 심쿵 하기도. 너무나 자유롭지만 정의감만큼은 투철한 미니언. 그 깜찍함을 만끽할 수 있는 뒤죽박죽 대소동의 한복판으로 뛰어들자!",
//         caution1 : "0",
//         caution2 : "1",
//         caution3 : "0",
//         caution4 : "1",
//         caution5 : "1",
//         caution6 : "1",
//         caution7 : "0",
//     },
//     {
//         idx : "12",
//         name : "미니언즈 피버 디스코 그리팅",
//         image : "attraction12",
//         explanation : "뒤죽박죽 그리팅에서 귀여운 디스코 의상을 입은 미니언즈와 함께 사진을 찍자!",
//         caution1 : "0",
//         caution2 : "0",
//         caution3 : "0",
//         caution4 : "0",
//         caution5 : "0",
//         caution6 : "0",
//         caution7 : "0",
//     },
//     {
//         idx : "13",
//         name : "바나나 카바나",
//         image : "attraction13",
//         explanation : "가장 좋아하는 바나나를 던져 주고, 미니언에게 선물을 받자!",
//         caution1 : "0",
//         caution2 : "0",
//         caution3 : "0",
//         caution4 : "0",
//         caution5 : "0",
//         caution6 : "0",
//         caution7 : "0",
//     },
//     {
//         idx : "14",
//         name : "버블 비트 블록",
//         image : "attraction14",
//         explanation : "HIPHOP 비트를 타고 펼쳐지는 버블을 사용한 신감각 하이 스킬 퍼포먼스!",
//         caution1 : "0",
//         caution2 : "0",
//         caution3 : "0",
//         caution4 : "0",
//         caution5 : "0",
//         caution6 : "0",
//         caution7 : "0",
//     },
//     {
//         idx : "15",
//         name : "버트와 애니의 원더 더 시",
//         image : "attraction15",
//         explanation : "미끄럼틀이 버트와 어니가 있는 볼 풀을 향해 뻗어 있네요. 용기 내서 미끄럼틀을 타고 내려가면 그곳은 파란색과 흰색 공이 가득한 바다! 해초가 하늘거리는 바닷속으로 잠수하거나 점프하면서 마음껏 헤엄치며 놀아요!",
//         caution1 : "0",
//         caution2 : "0",
//         caution3 : "0",
//         caution4 : "0",
//         caution5 : "0",
//         caution6 : "0",
//         caution7 : "0",
//     },
//     {
//         idx : "16",
//         name : "버트와 어니의 프로숍 게임 플레이스",
//         image : "attraction16",
//         explanation : "어트랙션과 쇼를 즐기는 사이사이에 가볍게 놀 수 있는 게임에 도전해 보자! 깜찍한 경품을 받을 수 있는 찬스!",
//         caution1 : "0",
//         caution2 : "0",
//         caution3 : "0",
//         caution4 : "0",
//         caution5 : "0",
//         caution6 : "0",
//         caution7 : "0",
//     },
//     {
//         idx : "17",
//         name : "빅드 비드 탑 서커스",
//         image : "attraction17",
//         explanation : "빅서커스 단장이 된 빅 버드. 빅 버드의 지시에 따라 동물들이 어슬렁어슬렁 주변을 돌고 있네요. 이 많은 동물을 타고 함께 빙글빙글.",
//         caution1 : "1",
//         caution2 : "1",
//         caution3 : "0",
//         caution4 : "1",
//         caution5 : "1",
//         caution6 : "0",
//         caution7 : "0",
//     },
//     {
//         idx : "18",
//         name : "빅 버드 빅 네스트",
//         image : "attraction18",
//         explanation : "센트럴 파크에 나타난 빅 버드의 둥지는 신나는 놀이공원이랍니다. 균형을 잡은 채 밧줄을 건너고 그물 위를 오르락내리락하면서 힘차게 몸을 움직여요! 씩씩하게 몸을 움직이자!",
//         caution1 : "0",
//         caution2 : "0",
//         caution3 : "0",
//         caution4 : "0",
//         caution5 : "0",
//         caution6 : "0",
//         caution7 : "0",
//     },
//     {
//         idx : "19",
//         name : "세서미 빅 드라이브",
//         image : "attraction19",
//         explanation : "마치 뉴욕 센트럴 파크를 달리고 있는 듯한 박력 있는 드라이브를 즐길 수 있는 라이드 어트랙션.",
//         caution1 : "0",
//         caution2 : "1",
//         caution3 : "0",
//         caution4 : "1",
//         caution5 : "0",
//         caution6 : "0",
//         caution7 : "0",
//     },
//     {
//         idx : "20",
//         name : "세서미 스트리트 4-D 무비 매직™",
//         image : "attraction20",
//         explanation : "오리지널 3-D 영화에 놀랍도록 새로운 차원의 효과가 더해진 4-D 엔터테인먼트. 세서미 스트리트™의 친구들, 엘모, 쿠키 몬스터, 빅 버드, 버트, 어니와 함께 바다로 잠수하고 하늘을 날아보아요. 상상 속의 세상을 온몸으로 느낄 수 있습니다.",
//         caution1 : "1",
//         caution2 : "1",
//         caution3 : "0",
//         caution4 : "1",
//         caution5 : "1",
//         caution6 : "0",
//         caution7 : "1",
//     },
//     {
//         idx : "21",
//         name : "슈렉 4-D 어드벤처",
//         image : "attraction21",
//         explanation : "드림웍스의 아카데미상 수상작 ‘슈렉’에서 탄생한 파크만의 오리지널 스토리. 슈렉, 동키와 함께 스릴 만점의 새로운 모험을 떠나자! 그곳은 3-D 영화에 새로운 차원의 특수 효과를 더한 4-D의 세계.",
//         caution1 : "1",
//         caution2 : "1",
//         caution3 : "0",
//         caution4 : "1",
//         caution5 : "1",
//         caution6 : "0",
//         caution7 : "1",
//     },
//     {
//         idx : "22",
//         name : "스누피 사운드 스테이지 어드벤처™",
//         image : "attraction22",
//         explanation : 
//         caution1 : "",
//         caution2 : "",
//         caution3 : "",
//         caution4 : "",
//         caution5 : "",
//         caution6 : "",
//     },
//     {
//         idx : "23",
//         name : "스페이스 킬러",
//         image : "attraction23",
//         explanation : 
//         caution1 : "",
//         caution2 : "",
//         caution3 : "",
//         caution4 : "",
//         caution5 : "",
//         caution6 : "",
//     },
//     {
//         idx : "24",
//         name : "스페이스 판타지 더 라이드",
//         image : "attraction24",
//         explanation : 
//         caution1 : "",
//         caution2 : "",
//         caution3 : "",
//         caution4 : "",
//         caution5 : "",
//         caution6 : "",
//     },

// ]